import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./template.module.css";
import Navbar from "@/Components/Navbar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={styles.body}>
        <div className={styles.mainpage}>
            <Navbar />
            {children}
        </div>
        </body>
        </html>
    );
}
